# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[de]
 languageCode = "de-de"
 contentDir = "content/de"
 copyright = "Julian Pawlowski &middot; [Impressum](/de/impressum/) &middot; [Datenschutzerklärung](/de/datenschutz/)"
