# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Über mich"
  url = "#ueber"
  weight = 10

[[main]]
  name = "Blog"
  url = "#lesenswert"
  weight = 20

[[main]]
  name = "Projekte"
  url = "#projekte"
  weight = 30

[[main]]
  name = "Vorträge"
  url = "#vortraege"
  weight = 35

[[main]]
  name = "Publikationen"
  url = "#hervorgehoben"
  weight = 40

[[main]]
  name = "Kontakt"
  url = "#kontakt"
  weight = 60

# [[main]]
#   name = "<i class='fas fa-rss'></i>"
#   url = "#abonnieren"
#   weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "Lebenslauf"
#    url = "files/lebenslauf.pdf"
#    weight = 70
