---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: content/en/post
  label: Blog posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content/en/publication
  label: Publications
  create: all
  match: "**/*"
- type: directory
  path: content/en/project
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/en
  label: Pages
  create: documents
  match: "*"
  exclude: _index.* index.*
- type: heading
  label: Deutsch
- type: directory
  path: content/de/post
  label: Blogbeiträge
  create: all
  match: "**/*"
  templates:
  - blogbeitrag
- type: directory
  path: content/de/publication
  label: Veröffentlichungen
  create: all
  match: "**/*"
- type: directory
  path: content/de/project
  label: Projekte
  create: all
  match: "**/*"
- type: directory
  path: content/de
  label: Seiten
  create: documents
  match: "*"
  exclude: _index.* index.*
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.56.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.56.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
version: 0.56.0
