---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/post
  label: EN/Blog Posts
  create: all
  match: "**/*"
- type: directory
  path: content/publication
  label: EN/Publications
  create: all
  match: "**/*"
- type: directory
  path: content/project
  label: EN/Projects
  create: all
  match: "**/*"
- type: directory
  path: content/authors
  label: EN/Authors
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: EN/About
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: EN/Homepage
  create: documents
  match: "**/*"
- type: document
  path: content/en/privacy.md
  label: EN/Privacy
- type: document
  path: content/en/legal.md
  label: EN/Legal
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.56.0
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.56.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
version: 0.56.0
