---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: summary
  label: summary
- type: list
  name: tags
  label: tags
- type: datetime
  name: date
  label: date
- type: field_group
  name: image
  label: image
  fields:
  - type: text
    name: caption
    label: caption
  - type: text
    name: focal_point
    label: focal_point
- type: field_group_list
  name: links
  label: links
  fields:
  - type: text
    name: icon
    label: icon
  - type: text
    name: icon_pack
    label: icon_pack
  - type: text
    name: name
    label: name
  - type: text
    name: url
    label: url
